name: GitHub Actions PR Merge Trigger Demo

on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: trigger Job on PR Merge
      uses: appleboy/jenkins-action@master
      with:
        url: "https://factually-close-doberman.ngrok-free.app"
        user: "arvin"
        token: ${{ secrets.JENTKINSTOKEN }}
        job: "testpipeline"